gText_Birch_Welcome::
	.string "Hi, you must be the new lab assistant!\p"
	.string "Sorry to keep you waiting!\p"
	.string "There was some urgent business I had\n"
	.string "to take care of first.\p"
	.string "Welcome to the POKéMON PUZZLE LAB!\p"
	.string "My name is Professor Birch.\p"
	.string "Now, let me fill you in on what your\n"
	.string "task here is going to be.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is the POKéMON Mew.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "We were able to catch it.\n"
	.string "As you know, this Pokemon can\l"
	.string "transform into any species it wants.\p"
	.string "It turns out its ability to transform\n"
	.string "is more vast than we could ever\l"
	.string "have imagined.\p"
	.string "Mew can not only transform itself,\n"
	.string "it can transform other objects as well.\p"
	.string "In our current experiments we let Mew\n"
	.string "roam free in rooms full of different\l"
	.string "objects to observe what it transforms\l"
	.string "them into.\p"
	.string "To our surprise, it likes to create\n"
	.string "puzzles. Yes, you heard that right.\p"
	.string "Now, your job as lab assistant will be to\n"
	.string "solve the puzzles Mew creates, hoping\l"
	.string "that we can find out why Mew does it.\p"
	.string "You must be thinking why it doesn't\n"
	.string "just escape if it can transform\l"
	.string "anything into anything?\p"
	.string "Well, that we don't know either.\p"
	.string "But one step at a time.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "Lab registration first.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Okay, that's all for now.\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Are you ready?\p"
	.string "I hope you got a good nights sleep\n"
	.string "because some puzzles may be hard to\l"
	.string "solve.\p"
	.string "$"
